[env:lilygo-t5-47]
platform = espressif32@^6.5.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCONFIG_SPIRAM_USE_MALLOC
lib_deps =
    https://github.com/Xinyuan-LilyGO/LilyGo-EPD47.git
    bblanchon/ArduinoJson@^7
    https://github.com/bitbank2/PNGdec.git
